author: "Orest Kulik <orest at nisdom.com>"
category: "offline"
summary: "My Ejabberd offline module using external HTTP services"
home: "https://github.com/okulik/mod_offline_my"
url: "git@github.com:okulik/mod_offline_my.git"
